FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the application code
COPY data_pipline.py ./
COPY measurements_coding_challenge.csv ./

# Install required dependencies (if needed)
RUN pip install pandas numpy

# Set the entry point to run the Python script
CMD ["python", "data_pipline.py"]